kind: pipeline
name: default

steps:
- name: build
  image: golang:1.12.7-alpine3.10
  commands:
    - apk add git gcc
    - go build -a -ldflags '-linkmode external -extldflags "-static"' -o kbdlight

- name: publish
  image: plugins/github-release
  settings:
    api_key: 
      from_secret: github_token
    files: kbdlight
    checksum:
      - sha512
  when:
    event: tag